package directory

// DefaultRecipients is the built-in directory of Ukrainian government bodies.
// Updated 2026-06-13 (OSINT-verified 9 dead addresses): Verified FOI-specific email addresses from OSINT research.
var DefaultRecipients = []Recipient{
	// CENTRAL
	{ID: "kmu", Name: "Кабінет Міністрів України", Email: "pr-zapit@kmu.gov.ua", Category: "central"},
	{ID: "rada", Name: "Верховна Рада України", Email: "infzapit@rada.gov.ua", Category: "central"},
	{ID: "op", Name: "Офіс Президента України", Email: "req@apu.gov.ua", Category: "central"},
	{ID: "minjust", Name: "Міністерство юстиції", Email: "callcentre@ca.minjust.gov.ua", Category: "central"},
	{ID: "minfin", Name: "Міністерство фінансів", Email: "publishinfo@minfin.gov.ua", Category: "central"},
	{ID: "minekonomiky", Name: "Мінекономіки", Email: "zapyt@me.gov.ua", Category: "central"},
	{ID: "moz", Name: "Міністерство охорони здоров'я", Email: "info@moz.gov.ua", Category: "central"},
	{ID: "mon", Name: "Міністерство освіти і науки", Email: "informzapyt@mon.gov.ua", Category: "central"},
	{ID: "mintsyfra", Name: "Мінцифра", Email: "zapit@thedigital.gov.ua", Category: "central"},
	{ID: "minoborony", Name: "Міністерство оборони", Email: "zapytmou@post.mil.gov.ua", Category: "central"},
	{ID: "minveteran", Name: "Мін-во у справах ветеранів", Email: "publicinfo@mspu.gov.ua", Category: "central"},
	{ID: "minregion", Name: "Мінрегіон", Email: "miu@mtu.gov.ua", Category: "central"},
	{ID: "mininfra", Name: "Міністерство інфраструктури", Email: "info@mtu.gov.ua", Category: "central"},
	{ID: "minenv", Name: "Міністерство захисту довкілля", Email: "zapyt@mepr.gov.ua", Category: "central"},
	{ID: "minsocpol", Name: "Міністерство соціальної політики", Email: "infozapit@mlsp.gov.ua", Category: "central"},
	{ID: "minmolodsport", Name: "Міністерство молоді та спорту", Email: "vidkrytist@mms.gov.ua", Category: "central"},
	{ID: "mfa", Name: "Міністерство закордонних справ", Email: "public.info@mfa.gov.ua", Category: "central"},
	{ID: "menrg", Name: "Міністерство енергетики", Email: "kanc@mev.gov.ua", Category: "central"},
	{ID: "ombudsman", Name: "Уповноважений ВРУ з прав людини", Email: "zapyt@ombudsman.gov.ua", Category: "central"},
	{ID: "dkp", Name: "Казначейська служба", Email: "info@treasury.gov.ua", Category: "central"},
	{ID: "dps", Name: "Податкова служба", Email: "publicinfo_dps@tax.gov.ua", Category: "central"},
	{ID: "customs", Name: "Митна служба", Email: "publishinfo@customs.gov.ua", Category: "central"},
	{ID: "dss", Name: "Державна служба статистики", Email: "info@ukrstat.gov.ua", Category: "central"},
	{ID: "dms", Name: "Міграційна служба", Email: "hotline@dmsu.gov.ua", Category: "central"},
	{ID: "dsns", Name: "ДСНС", Email: "info@dsns.gov.ua", Category: "central"},
	{ID: "pension", Name: "Пенсійний фонд", Email: "info@pfu.gov.ua", Category: "central"},
	{ID: "amku", Name: "Антимонопольний комітет", Email: "zvr@amcu.gov.ua", Category: "central"},
	{ID: "rp", Name: "Рахункова палата", Email: "zapyt@rp.gov.ua", Category: "central"},
	// LAW ENFORCEMENT
	{ID: "gpu", Name: "Офіс Генпрокурора", Email: "office@gp.gov.ua", Category: "law"},
	{ID: "mvs", Name: "МВС", Email: "vidkrytist@mvs.gov.ua", Category: "law"},
	{ID: "nabu", Name: "НАБУ", Email: "publichna.info@nabu.gov.ua", Category: "law"},
	{ID: "nazk", Name: "НАЗК", Email: "info@nazk.gov.ua", Category: "law"},
	{ID: "npu", Name: "Національна поліція", Email: "vidkrytist@police.gov.ua", Category: "law"},
	{ID: "sbu", Name: "СБУ", Email: "callcenter@ssu.gov.ua", Category: "law"},
	{ID: "dbr", Name: "ДБР", Email: "public@dbr.gov.ua", Category: "law"},
	{ID: "sap", Name: "САП", Email: "info@sap.gov.ua", Category: "law"},
	{ID: "vaks", Name: "ВАКС", Email: "inbox@vaks.gov.ua", Category: "law"},
	{ID: "esbu", Name: "ДБЕ", Email: "publicinfo@esbu.gov.ua", Category: "law"},
	{ID: "dpsu", Name: "Прикордонна служба", Email: "publicinfo@dpsu.gov.ua", Category: "law"},
	{ID: "dkr", Name: "Державна аудиторська служба", Email: "post@dasu.gov.ua", Category: "law"},
	// KYIV
	{ID: "kmda", Name: "КМДА", Email: "publicinfo@kyivcity.gov.ua", Category: "kyiv"},
	{ID: "kmr", Name: "Київська міська рада", Email: "zapit@kmr.gov.ua", Category: "kyiv"},
	{ID: "kyiv_police", Name: "Поліція Києва", Email: "vidkrytist.kyiv@police.gov.ua", Category: "kyiv"},
	{ID: "kyiv_proc", Name: "Прокуратура Києва", Email: "public@kyiv.gp.gov.ua", Category: "kyiv"},
	{ID: "kyivteploenergo", Name: "Київтеплоенерго", Email: "info@kte.kmda.gov.ua", Category: "kyiv"},
	{ID: "kyivvodokanal", Name: "Київводоканал", Email: "info@vodokanal.kiev.ua", Category: "kyiv"},
	{ID: "kyiv_dbr", Name: "ТУ ДБР у Києві", Email: "tu_kyiv@dbr.gov.ua", Category: "kyiv"},
	{ID: "kyiv_obl_admin", Name: "Київська ОДА", Email: "info@koda.gov.ua", Category: "kyiv"},
	{ID: "kyiv_obl_rada", Name: "Київська обласна рада", Email: "info@kor.gov.ua", Category: "kyiv"},
	// COURTS
	{ID: "pechersky_court", Name: "Печерський суд Києва", Email: "inbox@pc.ki.court.gov.ua", Category: "courts"},
	{ID: "shevchenkivsky_court", Name: "Шевченківський суд Києва", Email: "inbox@sh.ki.court.gov.ua", Category: "courts"},
	{ID: "solomyansky_court", Name: "Солом'янський суд Києва", Email: "inbox@sl.ki.court.gov.ua", Category: "courts"},
	{ID: "kmoas", Name: "Київський окружний адмінсуд", Email: "inbox@kmoas.court.gov.ua", Category: "courts"},
	{ID: "supreme_court", Name: "Верховний Суд", Email: "inbox@supreme.court.gov.ua", Category: "courts"},
	{ID: "kyiv_appeal_court", Name: "Апеляційний суд Києва", Email: "inbox@kia.court.gov.ua", Category: "courts"},
	{ID: "cass_admin", Name: "Касаційний адмінсуд", Email: "kas@supreme.court.gov.ua", Category: "courts"},
	{ID: "cass_civil", Name: "Касаційний цивільний суд", Email: "kcs@supreme.court.gov.ua", Category: "courts"},
	{ID: "cass_crim", Name: "Касаційний кримінальний суд", Email: "kks@supreme.court.gov.ua", Category: "courts"},
	{ID: "dsa", Name: "Державна судова адміністрація", Email: "vidkrytist@court.gov.ua", Category: "courts"},
	// ZAPORIZHIA
	{ID: "zoda", Name: "Запорізька ОВА", Email: "zapit@zoda.gov.ua", Category: "zaporizhia"},
	{ID: "zp_rada", Name: "Запорізька міська рада", Email: "zapit@zp.gov.ua", Category: "zaporizhia"},
	{ID: "zp_oblrada", Name: "Запорізька обласна рада", Email: "info@zor.gov.ua", Category: "zaporizhia"},
	{ID: "zp_police", Name: "Поліція Запоріжжя", Email: "info@zp.police.gov.ua", Category: "zaporizhia"},
	{ID: "zp_proc", Name: "Прокуратура Запоріжжя", Email: "public@zap.gp.gov.ua", Category: "zaporizhia"},
	{ID: "zp_dbr", Name: "ТУ ДБР у Мелітополі", Email: "info@mel.dbr.gov.ua", Category: "zaporizhia"},
	// OTHER REGIONS
	{ID: "lviv_admin", Name: "Львівська ОВА", Email: "zapit@loda.gov.ua", Category: "other"},
	{ID: "lviv_rada", Name: "Львівська міська рада", Email: "zaput@city-adm.lviv.ua", Category: "other"},
	{ID: "dnipro_admin", Name: "Дніпропетровська ОВА", Email: "zapit@dp.gov.ua", Category: "other"},
	{ID: "kharkiv_admin", Name: "Харківська ОВА", Email: "zapit@kharkivoda.gov.ua", Category: "other"},
}
